/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file RangeFinder.ino
 *
 * @author Christopher A. Bohn
 *
 * @brief Driver code for RangeFinder GroupLab.
 *
 ******************************************************************************/

/*
 * RangeFinder GroupLab (c) 2023 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include <CowPi.h>
#include "i2c_address.h"
#include "alarm.h"
#include "sensor.h"
#include "user_controls.h"


void setup() {
  cowpi_stdio_setup(9600);
  cowpi_set_display_i2c_address(I2C_ADDRESS);
  cowpi_setup(LCD1602 | I2C);
  cowpi_lcd1602_set_backlight(true);
  pinMode(9, OUTPUT);
  pinMode(2, OUTPUT);
  pinMode(3, INPUT);  // should already be that from cowpi_setup, but it doesn't hurt to be sure
  initialize_controls();
  initialize_sensor();
  initialize_alarm();
}

void loop() {
  manage_controls();
  manage_sensor();
  manage_alarm();
}
